14 generate types from a graphql schema
gjillo/gjillo-app pull request #20
Opened 2023-11-09 19:11 UTC by rubikon02

# Features

Type safety when using GraphQL

# Usage

1. Create `.graphql` file in `@graphql` directory
2. Run `npm run gql:generate` to generate once or `npm run gql:watch` to generate when changes are made
3. Use types from `@graphql/types`

## Server side example

```tsx
import {ProjectDocument} from "@graphql/types";

const { data } = await getClient().query({
    query: ProjectDocument,
    variables: {
        projectUuid: "abc..."
    },
});
```

### With props

```tsx
// ...
return <Project {...data.project!} />
```

```tsx
import {Project} from "@graphql/types";

function Project(props: Project) {
    // ...
}
```

## Client side example

```tsx
import {useQuery} from "@apollo/client";
import {ProjectDocument} from "@graphql/types";
import {Alert, LinearProgress} from "@mui/material";

const { loading, data, error } = useQuery(ProjectDocument, {
  variables: {
      projectUuid: props.uuid
  },
});
if (loading) return <LinearProgress />
if (error) return <Alert severity="error">{`${error}`}</Alert>
```

# Issues

Env variable `NEXT_PUBLIC_GQL_SERVER` cannot be used in `@graphql/codegen.ts` config:

```
× Invalid Codegen Configuration!                                                         
                                                                                         
        Please make sure that your codegen config file contains either the "schema" field
        or every generated file has its own "schema" field. 
```

2023-11-09 22:06 UTC, Spookyless requested changes
Add custom scalars to config:
https://stackoverflow.com/questions/74890201/how-to-add-custom-scalars-to-graphql-codegen

2023-11-09 22:06 UTC, Spookyless commented on app/project/[uuid]/page.tsx
> +            <Project {...data.project!} />
No Non-Null Assertion operators allowed - check if object is truthy instead

2023-11-09 22:08 UTC, Spookyless requested changes

2023-11-09 22:08 UTC, Spookyless commented on graphql/codegen.ts
> +    schema: process.env.NEXT_PUBLIC_GQL_SERVER,
Add as dev dependency to load env vars during codegen:
https://www.npmjs.com/package/dotenv-cli

2023-11-10 11:14 UTC, Spookyless requested changes

2023-11-10 11:14 UTC, Spookyless commented on graphql/scalars.graphql
Why delele this file? Now other graphql files will report that `UUID` is missing

2023-11-10 11:16 UTC, rubikon02 commented on graphql/scalars.graphql
Graphql files don't report anything and types are generated
![image](https://github.com/gjillo/gjillo-app/assets/31660898/55ba2d38-5495-4770-9b4c-32fa18061e83)

2023-11-10 11:17 UTC, rubikon02 commented on graphql/scalars.graphql
Timestamp was already used in project without definition in schema

2023-11-10 11:23 UTC, Spookyless commented on graphql/scalars.graphql
Right, because schema is taken from api now

2023-11-10 11:23 UTC, Spookyless approved these changes

2023-11-10 11:24 UTC, merged