Card details (modal window)
gjillo/gjillo-app pull request #23
Opened 2023-11-13 14:42 UTC by ShatterPlayer

Resolves #9.
Base modal window for card details. Contains dummy data temporarily. 
![image](https://github.com/gjillo/gjillo-app/assets/40521610/d67765aa-f278-4d5b-87e0-d61fe8f29a7b)

2023-11-13 14:54 UTC, Spookyless requested changes
![image](https://github.com/gjillo/gjillo-app/assets/42909064/b8224963-ffb9-4756-a77a-5076e0d788bc)

1. What is the purpose of this field? If those are labels then we have a duplicate with "Etykiety"
2. We don't store information about the creator of the card
3. not an issue anymore
4. not an issue anymore
5. What's the purpose of this field?
6. What's the purpose of this field? If it's read only, it shouldn't look like an input
7. Card is done iff it belong in a column of type `done`, not through checkbox

2023-11-16 11:33 UTC, ShatterPlayer commented
![image](https://github.com/gjillo/gjillo-app/assets/40521610/60c152e5-81c9-4e8e-a5f6-3c07145a7f79)

2023-11-18 11:32 UTC, rubikon02 approved these changes

2023-11-19 15:13 UTC, Spookyless approved these changes

2023-11-19 18:07 UTC, merged