Column with cards
gjillo/gjillo-app pull request #6
Opened 2023-11-03 14:20 UTC by ShatterPlayer

Resolves #1.
![image](https://github.com/gjillo/gjillo-app/assets/40521610/0c990e12-a6a9-4033-a1c7-53406189252d)

2023-11-03 14:35 UTC, Spookyless commented
`Column` component requires `name` prop, but you didn't update the place where they're used (`app/page.jsx`)

2023-11-03 14:45 UTC, rubikon02 requested changes

2023-11-03 14:45 UTC, rubikon02 commented on components/Column/index.tsx
> +interface ColumnProps {
Column should have:
- type - enum ('todo', 'in progress', 'done') or null for milestone tracking
- optional description (text)
- order (int)

2023-11-03 14:45 UTC, rubikon02 commented on components/Task/index.tsx
> +interface TaskProps {
Task should have order (int)

2023-11-03 14:45 UTC, rubikon02 commented on components/Task/index.tsx
- Rename to card
- Change naming to differentiate between column card and modal card

2023-11-03 18:10 UTC, Spookyless commented on components/Column/index.tsx
> +interface ColumnProps {
Order should not be a prop - the column doesn't need to know what order it is, displaying them in correct order is a job of the project view

2023-11-03 18:10 UTC, Spookyless commented on components/Task/index.tsx
> +interface TaskProps {
No order, again

2023-11-03 22:18 UTC, ShatterPlayer commented on components/Task/index.tsx
Task component has been renamed to ColumnCard (134a86aab4e6bd8af361d8a2886c1b1c3dda3a62)

2023-11-04 12:33 UTC, Spookyless approved these changes

2023-11-04 12:45 UTC, rubikon02 approved these changes

2023-11-04 13:00 UTC, merged